### PR TITLE
changed format to YYYY-MMM-DD

### PR DESCRIPTION
**Pull request by vyaspranjal33**
addressed the [issue 20](https://github.com/webvr-india/activities/issues/20)

### CODE REVIEW

**Review by shahbaz17 — COMMENTED** [review]
In few file, file name is missing - (hyfen) in between name

**Comment by vyaspranjal33** [comment]
will look in to @shahbaz17

**Comment by vyaspranjal33** [comment]
fixed all @shahbaz17

**Comment by lavish205** [comment]
@vyaspranjal33 @shahbaz17 PR should have a single commit always so that its easy to revert if something wrong happen.

**Comment by vyaspranjal33** [comment]
sorry for multiple commits i will try to take care of it @lavish205

**Pull request merged**
